---
layout: page
title: "20분만에 끝내는 딥러닝"
subtitle: "전이학습(Transfer Learning)"
author:
  name: "[한국 R 사용자회](https://r2bit.com/)"
output:
  html_document: 
    theme:
      version: 4
    include:
      after_body: assets/footer.html
      before_body: assets/header.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
urlcolor: blue
linkcolor: bluee
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
header-includes: 
  - \usepackage{tikz}
  - \usetikzlibrary{matrix,chains,positioning,decorations.pathreplacing,arrows}
---

```{r setup, include=FALSE}
# source("tools/chunk-options.R")
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(tidyverse)
```

# resnet {.tabset}

```{r}
library(keras)
library(EBImage)
library(tensorflow)

# Pretrained model
pretrained <- application_resnet50(weights = "imagenet")
summary(pretrained)


img <- image_load(glue::glue("{here::here()}/data/flag.png"), target_size = c(224,224))
x <- image_to_array(img)

plot(as.raster(x, max = 255))


x <- array_reshape(x, c(1, dim(x)))
x <- imagenet_preprocess_input(x)

resnet50 <- application_resnet50(weights = "imagenet")

preds <- resnet50 %>% 
  predict(x) %>% 
  imagenet_decode_predictions(top = 5)

preds


```


```{r}
data <- dataset_cifar10()
trainx <- data$train$x
testx <- data$test$x
trainy <- to_categorical(data$train$y, num_classes = 10)
testy <- to_categorical(data$test$y, num_classes = 10)

# Plot of first 64 pictures
par(mfrow = c(8,8), mar = rep(0, 4))
for (i in 1:64) plot(as.raster(trainx[i,,,], max = 255))
par(mfrow = c(1,1))

x <- resize(trainx[2,,,], w = 224, h = 224)
x <- array_reshape(x, c(1, dim(x)))
x <- imagenet_preprocess_input(x)
preds <- pretrained %>% predict(x)
imagenet_decode_predictions(preds, top = 5)[[1]]


```


