---
layout: page
title: "딥러닝"
subtitle: "딥러닝 기본기"
author:
  name: "에이아이에스 / [한국 R 사용자회](https://r2bit.com/)"
date: "2022-09-25"
output:
  html_document: 
    theme:
      version: 4
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
urlcolor: blue
linkcolor: bluee
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
---

```{r, include=FALSE}
# source("tools/chunk-options.R")
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(here)
```


# 딥러닝 개발영역


```{r deep-learing-list}
library(tidyverse)
library(bs4cards)

deep_learning_list <- list(
  tibble(
    title = "인공지능과 딥러닝",
    image = "assets/favicon-ai.png",
    text = "자동화, 딥러닝, 그리고 인공지능",
    link = "slideshow/index.html",
    footer = "2022-06-28"
  ),
  tibble(
    title = "딥러닝 개념",
    image = "assets/favicon-concept.png",
    text = "Attention, Dropout, ...",
    link = "00_concept.html",
    footer = "2022-06-22"
  ),
  tibble(
    title = "딥러닝 2.0",
    image = "assets/favicon-deep-learning.png",
    text = "딥러닝 2.0 - Transfer Learning, Transformers, 하드웨어, 딥러닝 프레임워크",
    link = "01_deep_learning.html",
    footer = "2022-07-11"
  ),
  tibble(
    title = "통계모형",
    image = "assets/favicon-statmodel.png",
    text = "선형 회귀모형, 로지스틱 회귀모형과 신경망",
    link = "01_stat_models.html",
    footer = "2022-06-29"
  ),
  tibble(
    title = "딥러닝 프레임워크",
    image = "assets/favicon-framework.png",
    text = "케라스, 텐서플로우, 파이토치 ...",
    link = "03_framework.html",
    footer = "2022-06-23"
  ),
  tibble(
    title = "파이토치",
    image = "assets/favicon-pytorch.png",
    text = "파이토치(Pytorch) 딥러닝 모형",
    link = "20_pytorch.html",
    footer = "2022-06-29"
  ),
  tibble(
    title = "자연어처리",
    image = "assets/favicon-transfer-NLP.png",
    text = "자연어 처리 - TF-IDF, 워드임베딩, RNN(LSTM), Transformer/Attention, BERT/GPT, 전이학습, ...",
    link = "30_NLP.html",
    footer = "2022-06-30"
  ),
  tibble(
    title = "전이학습 - NLP",
    image = "assets/favicon-transfer.png",
    text = "사전학습 모형(Pretrained model), 전이학습(transfer learning)",
    link = "31_transformers.html",
    footer = "2022-06-29"
  ),
  tibble(
    title = "전이학습 - Vision",
    image = "assets/favicon-transfer-vision.png",
    text = "사전학습 모형(Pretrained model), 전이학습(transfer learning), resent",
    link = "32_transfer-vision.html",
    footer = "2022-07-03"
  ),
  tibble(
    title = "딥러닝 서버",
    image = "assets/favicon-hardware.png",
    text = "GPU, CPU, SSD, ...",
    link = "40_hardware.html",
    footer = "2022-07-03"
  ),
  tibble(
    title = "딥러닝 개발 환경",
    image = "assets/favicon-stack.png",
    text = "딥러닝 개발환경과 소프트웨어 스택",
    link = "50_software_stack.html",
    footer = "2022-07-07"
  ),
  tibble(
    title = "AutoKeras",
    image = "assets/favicon-autokeras.png",
    text = "딥러닝 모형 개발 자동화",
    link = "60_model_automation.html",
    footer = "2022-07-10"
  ),
  tibble(
    title = "X-Shot Learning",
    image = "assets/favicon-xshot.png",
    text = "knn, 샴 네트워크, YOLO(Darkent) ...",
    link = "70_xshot_learning.html",
    footer = "2022-07-12"
  ),
  tibble(
    title = "사설 클라우드",
    image = "assets/favicon-cloud.png",
    text = "사설 클라우드(Private Cloud), NAS, 홈 네트워크",
    link = "private_cloud.html",
    footer = "2022-07-29"
  ),
  tibble(
    title = "NAS",
    image = "assets/favicon_nas.png",
    text = "시놀로지 NAS",
    link = "synology_nas.html",
    footer = "2022-07-29"
  ),
  tibble(
    title = "허깅페이스",
    image = "assets/favicon-hf.png",
    text = "허깅페이스(모형, 데이터셋) ... NLP(Transformers)",
    link = "huggingface.html",
    footer = "2022-07-30"
  ),
  tibble(
    title = "ML 자동화",
    image = "assets/favicon-mlops.png",
    text = "CML, DVC, MLOps, ...",
    link = "mlops_dvc.html",
    footer = "2022-07-31"
  )  
)





deep_learning_tbl <- deep_learning_list %>% 
  enframe() %>% 
  unnest(value)

deep_learning_tbl %>% 
  cards(
    title = title,
    text = text,
    link = link,
    image = image,
    footer = footer,
    layout = "label-left", 
    width = 3
  )
```
 
# 관련 정보

- [편집기 - https://www.latex4technics.com/](https://www.latex4technics.com/)
- [$LaTeX$ - Equation Editor](https://www.codecogs.com/latex/eqneditor.php)
- [Classical ML Equations in LaTeX](https://blmoistawinde.github.io/ml_equations_latex/)
- [How to code a logistic regression in R from scratch](https://anderfernandez.com/en/blog/code-logistic-regression-r-from-scratch/)
- [THE ASIMOV INSTITUTE, THE NEURAL NETWORK ZOO](https://www.asimovinstitute.org/neural-network-zoo/)
- [NN-SVG: Publication-ready NN-architecture schematics](https://alexlenail.me/)
- [A visual guide to Recurrent Neural Networks](https://www.analyticsvidhya.com/blog/2021/06/a-visual-guide-to-recurrent-neural-networks/)
- [Time Series Prediction with LSTM Recurrent Neural Networks in Python with Keras](https://machinelearningmastery.com/time-series-prediction-lstm-recurrent-neural-networks-python-keras/)

