---
title: "20분만에 끝내는 딥러닝"
subtitle: "딥러닝 핵심 개념"
author: "이광춘 / 한국 R 사용자회"
institute: ""
date: "2022-07-01"
bibliography: "references.bib"
output:
  xaringan::moon_reader:
    css: 
      - [default]
      - css/SNU.css
      - css/nhsr-fonts.css
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: googlecode
      highlightLines: true
      highlightLanguage: ["r"]
      countIncrementalSlides: false
      ratio: "4:3"
      beforeInit: "macros.js"
    includes:
      after_body: [css/insert-logo.html]
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(tidyverse)
xaringanExtra::use_panelset()
# library(nhsrtheme)
# library(NHSRdatasets)
# set default options

options(
  htmltools.dir.version = FALSE, 
  htmltools.preserve.raw = FALSE,
  tibble.width = 60, tibble.print_min = 6,
  crayon.enabled = TRUE
)

knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, 
                      fig.align = 'center',
                      fig.width = 7.252,
                      fig.height = 4,
                      dpi = 300)

# uncomment the following lines if you want to use the NHS-R theme colours by default
# scale_fill_continuous <- partial(scale_fill_nhs, discrete = FALSE)
# scale_fill_discrete <- partial(scale_fill_nhs, discrete = TRUE)
# scale_colour_continuous <- partial(scale_colour_nhs, discrete = FALSE)
# scale_colour_discrete <- partial(scale_colour_nhs, discrete = TRUE)

library(showtext)

showtext::showtext_auto()

# GGPLOT THEME ------------------------------------------------------------

theme_election <- function(..., font = "나눔바른펜") {
  
  theme_bw(base_family = font)  %+replace%
    
    theme(
      
      #grid elements
      panel.grid.major.x = element_line(color='gray75'),
      panel.grid.minor.x = element_blank(),
      # axis.ticks = element_blank(),          #strip axis ticks
      
      #since theme_minimal() already strips axis lines, 
      #we don't need to do that again
      
      #text elements
      plot.title = element_text(             #title
        family = font,            #set font family
        size = 30,                #set font size
        face = 'bold',            #bold typeface
        hjust = 0,                #left align
        vjust = 2),               #raise slightly
      
      plot.subtitle = element_text(          #subtitle
        family = font,            #font family
        hjust = 0,                #left align        
        size = 17),               #font size
      
      plot.caption = element_text(           #caption
        family = font,            #font family
        size = 12,                 #font size
        hjust = 1),               #right align
      
      axis.title = element_text(             #axis titles
        family = font,            #font family
        size = 20),               #font size
      
      axis.text.x = element_text(            #margin for axis text
        margin=margin(5, b = 10),
        size = rel(1.5),
        family = font, face="bold"),
      
      axis.text.y = element_text(
        size = rel(1.5),
        colour = "gray35", 
        family = font, face="bold"),
      
      strip.text.x = element_text(
        size = rel(1.5), 
        colour = "black", family = font, face="bold" ),
      
      strip.background = element_rect(fill="gray95"),
      
      legend.position = "top",
      legend.title=element_text(size=12),
      legend.text=element_text(size=10)
      
    )
}


```


class: title-slide, left, bottom

# `r rmarkdown::metadata$title`
----
## **`r rmarkdown::metadata$subtitle`**
### `r rmarkdown::metadata$author`
### `r rmarkdown::metadata$date`

 
---
class: inverse, middle
name: automation
# 발표 개요 

----

.pull-left[


최근 각광받고 있는 **.warmyellow[딥러닝(Deep Learning)]** 은 
학문적으로 의미가 있을 뿐만 아니라 기술의 급격한 발전과
디지털 전환에 중요한 역할을 하고 있기 때문에
**컴퓨팅 사고력(Computational Thinking)**의 중요한 축인 
**.warmyellow[자동화(automation)]**을 떼고 생각할 수는 없다.

이에, 자동화, 인공지능, 딥러닝을 이해하고 
구현하는데 핵심적인 사항을 다뤄본다. 

]
 
.pull-right[   
.left[

1\. [자동화](#automation)

2\. [인공지능](#ai)

3\. **[.warmyellow[딥러닝]](#deep-learning)**
]
] <!--end of right-column-->  

<!--------------------------  1. 자동화 ----------------------------------------->

```{r child='01-automation.Rmd'}
```

<!--------------------------  2. 인공지능 ----------------------------------------->

```{r child='02-ai.Rmd'}
```

<!--------------------------  3. 딥러닝 ----------------------------------------->

```{r child='03-deep-learning.Rmd'}
```


<!--------------------------  N. 마무리 ----------------------------------------->

```{r child='goodbye.Rmd'}
```



